mysql_root_password: super-secure-password
mysql_databases:
  - name: guestbook_db
    encoding: latin1
    collation: latin1_general_ci
mysql_users:
  - name: example_user
    host: "%"
    password: similarly-secure-password
    priv: "guestbook_db.*:ALL"