- name: Ensure group for jboss service exists
  become: yes
  group: name= "{{ jboss_svc_username }}" state= present

- name: add OS user for jboss service
  become: yes
  user:
    name: "{{ jboss_svc_username }}"
    shell: "/sbin/nologin"
    home: "{{ jboss_rootdir }}"
    groups: "{{ jboss_svc_username }}"

- name: set owner for jboss folder
  become: yes
  file:
    path: "{{ jboss_rootdir }}"
    recurse: yes
    owner: "{{ jboss_svc_username }}"
    group: "{{ jboss_svc_username }}"
    mode: 0755

- debug:
    msg: "command for next task: fgrep -c {{ jboss_mgmt_username }} {{ jboss_rootdir }}/standalone/configuration/mgmt-users.properties"

- name: Check that the jboss mgmt exist
  become: yes
  command: "fgrep -c {{ jboss_mgmt_username }} {{ jboss_rootdir }}/standalone/configuration/mgmt-users.properties"
  register: mgmt_usr_exist
  ignore_errors: yes
# hint: fgrep -c returns count of string (e.g. zero if nothing found, 1 if user exist, 2 and more if something go wrong )   
# returned value in registered var is 'string', but returncode (.rc) of grep is 1 if not found
- debug:
    msg: "mgmt_usr_exist='{{ mgmt_usr_exist }}'"

- debug:
    msg: "command for next task: {{ jboss_bindir }}/add-user.sh -s {{ jboss_mgmt_username }} {{ jboss_mgmt_pass }}"

- name: add jboss mgmt user
  become: yes
  become_method: sudo
  become_user: "{{ jboss_svc_username }}"
  command: "{{ jboss_bindir }}/add-user.sh -s {{ jboss_mgmt_username }} {{ jboss_mgmt_pass }}"
  when: "mgmt_usr_exist.rc == 1" 
#    - "{{ jboss_bindir }}/add-user.sh -s -a {{ jboss_app_username }} {{ jboss_app_pass }}"

- debug:
    msg: "command for next task: fgrep -c {{ jboss_mgmt_username }} {{ jboss_rootdir }}/standalone/configuration/mgmt-users.properties"

- name: Check that the jboss app user exist
  become: yes
  ignore_errors: yes
  command: "fgrep -c {{ jboss_app_username }} {{ jboss_rootdir }}/standalone/configuration/mgmt-users.properties"
  register: app_usr_exist
  failed_when: "app_usr_exist.rc == 1"

- debug:
    msg: "command for next task: {{ jboss_bindir }}/add-user.sh -s -a {{ jboss_app_username }} {{ jboss_app_pass }}"

- name: add jboss app user
  become: yes
  become_method: sudo
  become_user: "{{ jboss_svc_username }}"
  command: "{{ jboss_bindir }}/add-user.sh -s -a {{ jboss_app_username }} {{ jboss_app_pass }}"
  when: app_usr_exist == 0 


#fgrep jbossmgmt /usr/local/share/wildfly/jboss-as-7.1.1.Final/standalone/configuration/mgmt-users.properties
#fgrep jbossapp /usr/local/share/wildfly/jboss-as-7.1.1.Final/standalone/configuration/application-users.properties
  