---
# tasks file for jboss
- name: install openjdk
  become: yes
  apt:
    name: openjdk-8-jdk
    state: latest
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- debug:
    msg: "System {{ inventory_hostname }} has OS type: {{ ansible_distribution }}"

- name: Check that the java app files already exists
  stat:
    path: "{{ jboss_dirname + '/' + jboss_configfile }}"
  register: dirstate

- debug:
    msg: "filepath {{ jboss_dirname + '/' + jboss_configfile }} state is {{ stat_result.dirstate.exists }}"
  
- name: Download app zip and Unarchive
  unarchive:
    src: jboss_repo
    dest: jboss_dirname
    remote_src: yes
    when: stat_result.dirstate.exists == False 
 
- name: Remove <elastic-load-balancer> section
  xml:
    path: "{{ jboss_dirname + '/' + jboss_configfile }}"
    xpath: /cumulogic-app/services/@elastic-load-balancer
    state: absent