---
# tasks file for jboss
- debug:
    msg: "System {{ inventory_hostname }} has OS type: {{ ansible_distribution }}"

- name: install openjdk, unzip
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - 'openjdk-8-jdk'
    - 'unzip'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Check that the jboss directory already exists
  become: yes
  stat:
    path: "{{ jboss_dirname }}"
  register: dirstate

- debug:
    msg: "filepath {{ jboss_dirname }} state exists {{ dirstate.stat.exists }}"

- name: Check that the jboss jar file already exists
  become: yes
  stat:
    path: "{{ jboss_dirname + '/' + jboss_jarfile }}"
  register: jarstate

- debug:
    msg: "filepath {{ jboss_dirname + '/' + jboss_configfile }} state exists {{ jarstate.stat.exists }}"

- name: Create subdir for jboss app if not exists
  become: yes
  file:
    path: "{{ jboss_dirname }}"
    state: directory
    mode: 0755
  when: dirstate.stat.exists == False

- name: Check that the jboss directory exists or not
  become: yes
  stat:
    path: "{{ jboss_dirname }}"
  register: dirstate

- debug:
    msg: "filepath {{ jboss_dirname }} state exists {{ dirstate.stat.exists }}"
  
- name: Download app zip and Unarchive
  become: yes
  unarchive:
    src: "{{ jboss_repo }}"
    dest: "{{ jboss_dirname }}"
    creates: "{{ jboss_dirname + '/' + jboss_jarfile }}"
    remote_src: yes
  when: jarstate.stat.exists == False and  dirstate.stat.exists == True

- name: Check that the jboss jar file exists or not
  become: yes
  stat:
    path: "{{ jboss_dirname + '/' + jboss_jarfile }}"
  register: filestate
 
- debug:
    msg: "filepath {{ jboss_dirname + '/' + jboss_jarfile }} state exists {{ jarstate.stat.exists }}"
 
- name: add OS user for jboss service
  user:
    name: "{{ jboss_svc_username }}"

- name: add jboss users
  shell: "{{ item }}"
  with_items:
    - 'sudo chown -fR {{ jboss_svc_username }}:{{ jboss_svc_username }} {{ jboss_rootdir }}'
    - 'su -c "add-user.sh {{ jboss_mgmt_username }} {{ jboss_mgmt_pass }}" {{ jboss_svc_username }}' 
    - 'su -c "add-user.sh -a {{ jboss_app_username }} {{ jboss_app_pass }}" {{ jboss_svc_username }}'
    