---
# tasks file for jboss
- name: install openjdk, unzip
  become: yes
  apt:
    name: "{{ items }}"
    state: latest
  with_items:
    - openjdk-8-jdk
    - unzip
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- debug:
    msg: "System {{ inventory_hostname }} has OS type: {{ ansible_distribution }}"

- name: Check that the java app files already exists
  become: yes
  stat:
    path: "{{ jboss_dirname + '/' + jboss_configfile }}"
  register: dirstate

- debug:
    msg: "filepath {{ jboss_dirname + '/' + jboss_configfile }} state exists {{ dirstate.stat.exists }}"

- name: Create subdir for jboss app if not exists
  become: yes
  file:
    path: "{{ jboss_dirname }}"
    state: directory
    mode: 0755
  when: dirstate.stat.exists == False

- debug:
    msg: "filepath {{ jboss_dirname + '/' + jboss_configfile }} state exists {{ dirstate.stat.exists }}"
  
- name: Download app zip and Unarchive
  become: yes
  unarchive:
    src: "{{ jboss_repo }}"
    dest: "{{ jboss_dirname }}"
    creates: "{{ jboss_dirname + '/' + jboss_configfile }}"
    remote_src: yes
  when: dirstate.stat.exists == False 
 
- name: Remove <elastic-load-balancer> section
  become: yes
  xml:
    path: "{{ jboss_dirname + '/' + jboss_configfile }}"
    xpath: /cumulogic-app/services/@elastic-load-balancer
    state: absent