---
# tasks file for jboss/wildfly
- debug: 
    msg: "System {{ inventory_hostname }} has OS type: {{ ansible_distribution }}"

- name: install openjdk, unzip
  become: yes
  apt: name="{{ item }}" state=latest
  with_items:
    - 'default-jdk'
    - 'unzip'
    - 'python-lxml'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include_tasks: 1-folder.yml
- include_tasks: 2-users.yml
- include_tasks: 3-service.yml 

   