---
# tasks file for mysql-gb-db
- debug:
    msg: "{{ mysql_databases[name] }}"
  
- name: Restore database
  mysql_db:
    name: "{{ mysql_databases[name] }}"
    login_user: "{{ mysql_users[name] }}"
    login_password: "{{ mysql_users[pasword] }}"
    state: import
    target: "{{ gb_dirname + '/' gb_dbdump }}"