- name: dependency provisioning
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: false
  tasks:
    - name: install python2
      raw: sudo apt-get -y install python-simplejson
      
- name: Include all .json and .jsn files in vars/all and all nested directories (2.3)
  hosts: all
  vars_files:
    - group_vars/all/params.json

- name: configure and deploy the webservers and application code
  hosts: web-servers
# not sure
# remote_user: root

  roles:
    - jboss
#    - guestbookapp

#- name: deploy MySQL and configure the databases
#  hosts: db-servers
# remote_user: root

#  roles:
#    - mysql-gb-db       