#- hosts: 127.0.0.1
#  tasks:
#  - name: Write nodes host pubkeys to local known hosts
#    connection: local
#    command: "ssh-keyscan -H {{ item }} >> /home/vagrant/.ssh/known_hosts"
#    with_items: "{{ hostvars[inventory_hostname]['groups']['all'] }}"
# moved to provisioning script
#  - debug:
#      msg: "ssh-keyscan -H {{ hostvars[inventory_hostname]['groups']['all'] }}"

      
- hosts: all
  name: Include all .json and .jsn files in vars/all and all nested directories (2.3)
  vars_files:
      - group_vars/all/params.json

- hosts: web-servers
  name: configure and deploy the webserver (jboss/wildfly)
  roles:
      - jboss

- name: deploy MySQL and configure the databases
  hosts: db-servers
  become: yes
  vars_files:
    - group_vars/db-servers/main.yml
  roles:
    - { role: geerlingguy.mysql }
    - mysql-gb-db

- hosts: web-servers
  name: configure and deploy the application code
  roles:
      - guestbookapp

